FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN pip install python-swiftclient python-keystoneclient --no-cache-dir

COPY ingest.py .
COPY generate_transactions.py .

ENTRYPOINT ["python", "ingest.py"]
